FROM node:21.7.1-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json .

# Update npm
RUN apk update && \
    apk add npm 

RUN npm install --include=dev


# Copy the rest of the application code
COPY . .

# Default to development, can be overridden in compose
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

CMD ["npm", "run", "dev"]