FROM node:21.7.1-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json .

# Update npm
RUN apk update && \
    apk add npm

RUN npm install

# Install dependencies
RUN npm ci

# Copy the rest of the application code
COPY . .

CMD ["npm", "run", "dev"]