
name: Deploy to Amazon ECS

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
          cd base/cirrostrats-frontend &&
          git pull origin dev &&
          docker compose --profile production up -d --build
        '

    - name: Remove dangling images - <none> type images
      run: docker image prune -af

    # Seems like this wont be necessary since volumes bloat issue has been fixed
    # - name: Cleanup Dangling Images, Volumes, and Build Cache
      # run: docker system prune -a -f --volumes

    - name: Remove build cache
      run: docker builder prune -f