name: Test & Deploy to Amazon ECS

on:
  push:
    branches: ["isolated-test"]
  workflow_dispatch:
    inputs:
      run_tests_only:
        description: "Run only tests (skip deployment)"
        required: false
        default: "true"
        type: boolean

env:
  CI: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # Setup repository structure
      - name: Setup repositories
        run: |
          git clone https://github.com/Cirrostrats/base.git base
          cd base
          git clone https://github.com/ujazishere/cirrostrats-backend.git
          cd cirrostrats-backend && git checkout dev && cd ..

      - name: Checkout frontend
        uses: actions/checkout@v4
        with:
          path: base/cirrostrats-frontend

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: base/cirrostrats-frontend/package-lock.json

      # Create .env files from secrets
      - name: Create environment files
        run: |
          cd base
          echo "${{ secrets.FRONTEND_ENV }}" > cirrostrats-frontend/.env
          echo "${{ secrets.BACKEND_ENV }}" > cirrostrats-backend/.env

      # Start services
      - name: Start services
        run: |
          cd base
          docker compose up -d --build

          # Wait for services to be ready
          sleep 5
          until curl -sf http://localhost:5173 && curl -sf http://localhost:8000; do
            echo "Waiting for services to be ready..."
            sleep 5
          done

      # Ensure any files produced by Docker (often as root) are re-owned by the runner
      - name: Fix workspace permissions after compose
        run: sudo chown -R $(id -u):$(id -g) base/cirrostrats-frontend

      # Run tests
      - name: Run tests
        run: |
          cd base/cirrostrats-frontend
          npm ci
          npx playwright install chromium --with-deps
          npm run test

      # Upload artifacts
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: base/cirrostrats-frontend/tests/integration/results/
          retention-days: 30

      # Cleanup
      - name: Cleanup
        if: always()
        run: |
          cd base
          docker compose down
          docker system prune -af

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.event.inputs.run_tests_only != 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to AWS
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
            cd base/cirrostrats-frontend &&
            git pull origin isolated-test &&
            # In case you wanted to rebuild - but this causes crash on lightweight instances hence commented out.
            # docker compose up -d frontend --build &&
            docker system prune -af
          '
